name: Publish to JetBrains Marketplace

on:
  release:
    types:
      - created

permissions:
  contents: read

jobs:
  publish:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4.1.0
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Publish to JetBrains Marketplace
        env:
          GIT_TAG: ${{github.ref_name}}
          CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: ./gradlew publishPlugin
